---
- name: Setup | Add vagrant to sudoers
  lineinfile:
    "dest=/etc/sudoers
    state=present
    regexp='^vagrant ALL'
    line='vagrant ALL=(ALL) NOPASSWD: ALL'"

- name: Setup | Locale gen
  locale_gen: name=en_AU.UTF-8 state=present

- name: Setup | Install utility packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - build-essential
    - module-assistant
    - rsync
    - curl
    - git

