---
- include: tasks/base.yml
- include: tasks/php.yml
- include: tasks/nginx.yml
- include: tasks/mysql.yml 

- name: Node | Install packages
  npm: 
    name: "{{ item }}"
    global: yes
  with_items:
    - yarn
    - gulp

- name: Silverstripe | Add _ss_environment.php
  template:
    src: _ss_environment.php.j2
    dest: /vagrant/_ss_environment.php
