---
- name: NGINX | Create sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory

- name: NGINX | Add NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Add sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/debian/ jessie nginx"

- name: NGINX | Add sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/debian/ jessie nginx"

- name: NGINX | Update apt cache
  apt:
    update_cache: yes

- name: NGINX | Install
  apt:
    pkg: nginx
    state: latest

- name: NGINX | Start
  service:
    name: nginx
    state: started

- name: NGINX | Global config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: 
    - Restart nginx

- name: NGINX | Config default website
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-enabled/default.conf
    mode: 0644
  notify: 
    - Restart nginx

- name: NGINX | Check vhost folder and permissions
  file:
    path: "/vagrant"
    state: directory
    owner: "vagrant"
    group: "vagrant"
    mode: g+s,u=rwx,g=rwx,o=rx

